Sensor interactive automation
concord-consortium/sensor-interactive pull request #131
Opened 2022-12-19 18:37 UTC by saravanan-udayakumar

2022-12-21 05:28 UTC, tejal-shah commented
@saravanan-udayakumar , this seems like a pretty exhaustive suite, maybe a little more than I'd expect it to be. Any chance we can make them a little more concise? For example, it might make sense to have pause, on-demand, bar in one test and then not  have only bar-pause and bar-on-demand combinations separately.

2022-12-21 05:31 UTC, tejal-shah requested changes
Added a comment to consolidate a few tests

2022-12-21 14:08 UTC, saravanan-udayakumar commented
> @saravanan-udayakumar , this seems like a pretty exhaustive suite, maybe a little more than I'd expect it to be. Any chance we can make them a little more concise? For example, it might make sense to have pause, on-demand, bar in one test and then not have only bar-pause and bar-on-demand combinations separately.

@tejal-shah Updated. Deleted the individual combinations.

2022-12-23 19:38 UTC, tejal-shah approved these changes

2022-12-23 19:38 UTC, merged